import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GetServerSideProps } from "next";
import { fetchCategories } from "../http/index";

const inter = Inter({ subsets: ["latin"] });

function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-primary">Hello</h1>
      </main>
    </>
  );
}

export default Home;

// export const getServerSideProps: GetServerSideProps = async () => {
//   const { data }: AxiosResponse<ICollectionResponse> = fetchCategories();
//   console.log("data: ", data);
//   return {
//     props: { data },
//   };
// };
